services:
  livia:
    build: .
    container_name: livia
    ports:
      - 2259:2259
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017

  redis:
    image: redis:7-alpine
    container_name: redis

  mongo:
    image: mongo:7
    container_name: mongo